### ISSUE TITLE
Getting "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by jenbuzz** [addyosmani/grunt-uncss#100]
Any idea what this means:

(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded

I'm using the following setup:

Node version: 0.10.25
OS: Ubuntu 14.04 LTS 64-Bit
grunt-uncss: 0.3.3
grunt: 0.4.4

**Comment by deepaksisodiya** [comment]
I finally figured out a similar problem I was having with spell. I was using

grunt.registerTask('spell', [ 'spell']);
The trick was that Grunt doesn't seem to like the repetition in names. When I switch to

grunt.registerTask('spellCheck', [ 'spell']);
Everything worked as it should.

may this help you

**Comment by kildareflare** [comment]
I had the same problem with a stackoverflow and dan-lyn fix worked for me.
