### ISSUE TITLE
Feature - Accept sitemap.xml

### ISSUE THREAD

**Issue by thomaswelton** [addyosmani/grunt-uncss#103]
Instead of requiring the developer to pass in an array of files like 

``` js
uncss: {
  dist: {
    files: {
      'dist/css/tidy.css': ['app/index.html', 'app/about.html']
    }
  }
}
```

Allow for a sitemap to be passed instead

``` js
uncss: {
  dist: {
    files: {
      'dist/css/tidy.css': 'app/sitemap.xml'
    }
  }
}
```

The plugin should then parse the sitemap, extract the URLs and use them.
If this is something you think is possible I could possibly put together a PR for this feature as I think it'd be handy

**Comment by VladimirPlokhov** [comment]
+1

**Comment by vanhoofmaarten** [comment]
+1
