### ISSUE TITLE
Inline css seem ignored by uncss

### ISSUE THREAD

**Issue by mdemori** [addyosmani/grunt-uncss#107]
Hi,

I'm trying to use uncss through node code. My environment is Windows 7.

My code is really simple (i'm new to node), i use the example provided on GitHub with a really really simple file save addition.

When i execute the code, i take back an error `[Error: UnCSS: no stylesheets found]` so, as far as i can understand, seem that i cant parse inline style (`<style>` tag) wit uncss.
Is this a uncss limit that i miss or i done something wrong?

this is my simple node code:

```
var fs = require('fs');
var os = require('os');
var uncss = require('uncss');

var files   = ['./test_file.html'];

uncss(files, function (error, output) { 
try{
      if(error == ''){
    fs.writeFile(__dirname+'/'+'cleaned.html', output, function(err) {
    console.log('File written.');
   });
     process.exit(0);
}else{
 console.log(error);
 process.exit(1);
}
  } catch(e) {
    console.log(error);
    console.log(e);
    process.exit(1);
  }
});
```

this is  the test_file.html content (a really simple file wrote to test the program):

```
<!doctype html>
<html>
<head>
    <title>test page</title>
    <meta charset="UTF-8">
    <style>
        #test01{color:red;}
        .test02{color:blue;}
        .unusedToRemove01{color:black;}
        #unusedToRemove02{color:green;}
    </style>
</head>
<body>
    <div class="test02">test01</div>
    <div id="test01">test02</div>
</body>
</html>
```

**Comment by sparanoid** [comment]
I just create a fork of this repo doing the exact same thing, but does focus on processing the inline CSS only: https://github.com/sparanoid/grunt-uncss-inline

This plugin do the following things:

1. Search all `<style>` tags and combine all the inline CSS into one in the searching order.
2. Pass combined inline CSS to `uncss` for the cleanup.
3. Save cleaned CSS to the first `<style>` found in the DOM.
4. Remove all other deprecated `<style>` tags.
