### ISSUE TITLE
Should ignore outer css source

### ISSUE THREAD

**Issue by mofas** [addyosmani/grunt-uncss#13]
I use google font in my project, unfortunately, it will cause error report when I operate grunt-uncss task.

<code>Error: could not find: build\http:\fonts.googleapis.com\css?family=Caudex</code>

**Comment by ArmorDarks** [comment]
I'm not sure, but seems that similar error appeared again in 0.4.0 and higher versions:

``` coffee
###
Uncss
https://github.com/addyosmani/grunt-uncss
Remove unused CSS
###
module.exports = ->
  @config 'uncss',
    build:
      options:
        htmlroot: 'build'
      files: [
        src: 'build/{,**/}*.html'
        dest: build/assets/styles/style.tidy.css'
      ]
```

```html
	<!-- Fonts -->
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700&amp;subset=latin,cyrillic">
```

results in:
![39d5n5](https://cloud.githubusercontent.com/assets/4460311/6970136/3160d156-d97c-11e4-9fab-c86080431367.png)

Please note that there is nowhere can be found path `build\css` in project or microtemplate's variables, while actuals project's css stored in `build\assets\styles`

In 0.3.8 all is fine

**Comment by otravers** [comment]
I can replicate the issue as explained by @ArmorDarks with grunt 1.0.1 and grunt-uncss 0.6.1
