### ISSUE TITLE
Value for stylesheets option must be in brackets

### ISSUE THREAD

**Issue by sigo** [addyosmani/grunt-uncss#131]
Value for *stylesheets* option must be in *[* and *]* brackets. Even for one path. Why?

    stylesheets: 'css/style.css'

return

    Fatal error: Object css/style.css has no method 'map'

but

    stylesheets: ['css/style.css']

works great. Any others grunt tasks accept string and lists. Could you fix this?

**Comment by XhmikosR** [comment]
Closing for now. We stick to what upstream is using.

If you are interested in changing this, please make a pull request and CC me.
