### ISSUE TITLE
Dynamic generation of nodes with Bootstrap classes

### ISSUE THREAD

**Issue by ottomen** [addyosmani/grunt-uncss#133]
I'm using Bootstrap and such library as http://silviomoreto.github.io/bootstrap-select/ (custom select styling instead of native browser poor markup css possibilities). 
There is no classnames as .dropdown-toggle (and few others) in pure .html files, and only after bootstrap-select.js plugin initialize — node <pre><code>`<select class="selectpicker"></select>`</pre></code> transforms into 
<pre><code>`<div class="btn-group bootstrap-select"><button type="button" class="btn dropdown-toggle selectpicker btn-default"> ...`</pre></code>
But uncss is removed all css rules for .bootstrap-select, .dropdown-toggle, cause there is no such classes in html.
How can i prevent removing specific css riles for .bootstrap-select, .dropdown-toggle and other classes,  which are not used directly from html files and will be generated dynamically?

**Comment by syauqi** [comment]
> Yep, that helps.
> My first grunt plugins order was — 'sass', 'uncss', 'cssmin', 'watch'. Dynamic css selectors where removed in despite of existing regexps and ignore options of uncss. But when i changed the order of the plugins to 'sass', 'cssmin', 'uncss', 'watch' — all needed selectors where successfully ignored and stayed in stylesheet.
> Here is my Gruntfile.js:
> 
> ```
> module.exports = function(grunt) {
>     grunt.initConfig({
>         sass: {
>             dist: { 
>                 options: {
>                     style: 'expanded'
>                 },
>                 files: {
>                     'project/css/style.css': 'project/vendor/stylesheets/bootstrap.scss' 
>                 }
>             }
>         },
>         cssmin: {
>             minify: {
>                 expand: true,
>                 cwd: 'project/css/',
>                 src: ['*.css', '!*.min.css'],
>                 dest: 'project/css/',
>                 ext: '.min.css'
>             }
>         },
>         uncss: {
>             dist: {
>                 options: {
>                     ignore: ['.bootstrap-select.btn-group .dropdown-menu.open', 
>                     '.bootstrap-select.btn-group .dropdown-menu.inner', 
>                     '.bootstrap-select.btn-group .dropdown-toggle.selectpicker', 
>                     '.bootstrap-select.btn-group .dropdown-toggle.selectpicker .caret',
>                     '.selectpicker',
>                     '.bootstrap-select.btn-group .dropdown-menu.dropdown-menu>li>a',
>                     '.open',
>                     '.dropdown-menu.open',
>                     /open.*/,
>                     '.btn-group',
>                     '.inner',
>                     '.bootstrap-select.btn-group .dropdown-menu.inner']
>                 },
>                 files: {
>                     'project/css/style.min.css': ['project/index.html', 'project/main.html']
>                 }
>             }
>         },
>         watch: {
>             files: ['project/vendor/stylesheets/bootstrap/*', 'project/vendor/stylesheets/*'],
>             tasks: ['sass', 'cssmin', 'uncss'],
>         }
>     });
>     grunt.loadNpmTasks('grunt-contrib-watch');
>     grunt.loadNpmTasks('grunt-contrib-sass');
>     grunt.loadNpmTasks('grunt-contrib-cssmin');
>     grunt.loadNpmTasks('grunt-uncss');
>     grunt.registerTask('default', ['sass', 'cssmin', 'uncss', 'watch']);
> };
> ```
> 
> All is working properly.

Thanks for this, im too lazy to write every selector that you write hehe
