### ISSUE TITLE
Object build/html/index.html has no method 'forEach'

### ISSUE THREAD

**Issue by khalwat** [addyosmani/grunt-uncss#141]
I've looked at the examples on the github page, but this has me scratching my head as to why it's not working.  Grunt file:

```js
uncss: {
    dist: {
        files: [
            {src: ['build/html/index.html'], dest: 'public/css/site.tidy.min.css'},
        ],
        options: {
            stylesheets: ['public/css/site.combined.min.css'],
        },
    },
},
```

I've tried all sorts of grunt file syntax variants for build/html/index.html, to no avail.

I feel like I'm missing something very simple, but I'm at a loss for what that is.  build/html/index.html does exist, and it contains one css stylesheet link in it (which I override anyway in options, but...):

```html
	<link rel="stylesheet" type="text/css" href="/css/site.combined.min.css"/>
```

Running the above with --verbose I'm still not seeing anything too helpful:

	grunt uncss --verbose

...

	Registering "grunt-uncss" local Npm module tasks.
	Reading /var/www/pga/node_modules/grunt-uncss/package.json...OK
	Parsing /var/www/pga/node_modules/grunt-uncss/package.json...OK
	Loading "uncss.js" tasks...OK
	+ uncss
	Loading "Gruntfile.js" tasks...OK
	+ all, default
	Running tasks: uncss
	Running "uncss" task
	Running "uncss:dist" (uncss) task
	Verifying property uncss.dist exists in config...OK
	Files: build/html/index.html -> public/css/site.tidy.min.css
	Options: report="min", stylesheets="public/css/site.combined.min.css"
	Warning: Object build/html/index.html has no method 'forEach' Use --force to continue.

**Comment by jtwalters** [comment]
Easy fix:

Patch: Change `f.orig.src` to `f.src`.

**Comment by amejias101** [comment]
Is there a solution to this issue? I'm having the same issue with something as simple as:
```
  uncss: {
      dist: {
        files: {
          'css/styles.min.cleaneds.css': ['.tmp/templates/home.html'],
        }
      }
    },
```

**Comment by jtwalters** [comment]
You need to patch the source package with my change above.

**Comment by XhmikosR** [comment]
We really need a test case for this.

**Comment by XhmikosR** [comment]
This shouldn't happen with the latest release.
