### ISSUE TITLE
ReactJS components and uncss

### ISSUE THREAD

**Issue by joeyhipolito** [addyosmani/grunt-uncss#152]
I ran the uncss task and found out that it strips the styles of the component.
Can uncss be able to detect unused css, even with dynamically loaded components?

**Comment by addyosmani** [comment]
Dynamic CSS is a complex problem to 100% get right. It's possible to use timers with Phantom and scrape a version of the DOM at some point after the page has loaded. 

That is probably the best we can do as there's currently no way to capture CSS toggled by user behavior. Timers + an ignore sheet would probably get you what you're after.

**Comment by XhmikosR** [comment]
This is an upstream limitation...

**Comment by ArmorDarks** [comment]
You can also use prefixes for dynamic classes like `is-`, etc. and ignore them with `ignore` option in conjuration with regex

**Comment by addyosmani** [comment]
^ this is also true. Given that the dynamic side of this problem is not something we can tackle directly in `grunt-uncss` and as @XhmikosR  mentions is up to the upstream module, let's close this issue.
