### ISSUE TITLE
I cant get uncss to ignore my css class.

### ISSUE THREAD

**Issue by respectYourNeighbour** [addyosmani/grunt-uncss#155]
I have this classes inside my CSS.

.menu-icon.open {
    something...
}
.menu-icon.open > span:before {
    something...
}
.menu-icon.open > span:after {
    something...
}

The class ".menu-icon.open" get's applied from javaScript.

I'm passing '.menu-icon.open' to ignore and it works, but the other classes do not pass uncss.
How should I do this?

options: {
                ignore: ['.menu-icon.open', '.my-icon.open > span:before'],
                stylesheets: ['myFile.css']
            },

**Comment by XhmikosR** [comment]
This should be asked upstream.
