### ISSUE TITLE
ReferenceError: Can't find variable X

### ISSUE THREAD

**Issue by Sculdiner** [addyosmani/grunt-uncss#156]
Hello there, i'm pretty new here and still learning but i've spent my last 4 days trying to get this to work, so as a last resort i'm coming here to ask for help! I have a simple html file, where i inject a grid from a javascript file at runtime. When i run the grunt task, any css that i have, related to the original html DOM elements, gets uncss-ed correctly; but any css related to the javascript file, are cut off completely.. i read that this shouldn't be happening. the task warns me with "ReferenceError: Can't find variable X" (where X is the name of a function that i call in the .js file).
I would be grateful if anyone could help me out or point me in the right direction!!!

**Comment by XhmikosR** [comment]
That's an upstream issue.

Try using absolute paths in script and link tags.

**Comment by jnchapman** [comment]
I get the same error. Please can you unpack the cause of the error, this might help us work around it.
I have a single reference to the css bootstrap file in each of my 3 html files (validated html files)

<link rel="stylesheet" href="bootstrap/3.3.2/css/bootstrap.min.css">

Error
running "uncss:dist" (uncss) task
ReferenceError: Can't find variable: $

  file:///home/chapmj/Documents/test6/tests/app/index.html:32
ReferenceError: Can't find variable: $

  file:///home/chapmj/Documents/test6/tests/app/index.html:119
ReferenceError: Can't find variable: $

  file:///home/chapmj/Documents/test6/tests/app/index.html:137
Fatal error: UnCSS: could not open /css

**Comment by XhmikosR** [comment]
Try using absolute paths like /foo/bar.js.

**Comment by XhmikosR** [comment]
CC @giakki
