### ISSUE TITLE
I cannot get uncss to ignore my class.

### ISSUE THREAD

**Issue by respectYourNeighbour** [addyosmani/grunt-uncss#157]
I have this classes inside my CSS.

```css
.menu-icon.open {
     something...
}
.menu-icon.open > span:before {
     something...
}
.menu-icon.open > span:after {
     something...
}
```

The class `.menu-icon.open` get's applied from JavaScript.

I'm passing `.menu-icon.open` to ignore and it works, but the other classes (`... > span:after`) do not pass uncss.

This is how I tried to make uncss to ignore (`.my-icon.open > span:before`) and it didn't.

```js
options: {
     ignore: ['.menu-icon.open', '.my-icon.open > span:before'],
     stylesheets: ['myFile.css']
},
```

**Comment by carouselcreative** [comment]
I'm having the same problem using this demo: http://codyhouse.co/demo/back-to-top/index.html
The ignore array is not being ignored and are cut out of clean.css

	uncss: {
	  dist: {
	  		options: {
	  			ignore: ['.cd-is-visible', '.cd-fade-out', '.no-touch', ':hover'],
	  			stylesheets: ['css/style.css'],
	  			ignoreSheets: ['css/reset.css']
	  		},	
    	    files: {
	      		'../css/clean.css': ['../index.html']
	    }
	  }
	}

**Comment by XhmikosR** [comment]
This is an upstream issue.
