### ISSUE TITLE
// instead of http:// or  https://

### ISSUE THREAD

**Issue by jnchapman** [addyosmani/grunt-uncss#158]
Using 

```
  <link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
```

Grunt gives unspecific error, you don't know which file it occurs in.

Running "uncss:dist" (uncss) task
Fatal error: UnCSS: could not open /css
====================
using https://fonts... or http://fonts work correctly (no errors)

Not sure if it a bug but perhaps should go in the docs somewhere as a gotcha

**Comment by brunobatista** [comment]
+1

**Comment by addyosmani** [comment]
I still need to verify if this causes breakage, but this is something we could definitely be handling better.

**Comment by XhmikosR** [comment]
Protocol relative URLs work fine here.
