### ISSUE TITLE
Support alternative search path in usemin markup

### ISSUE THREAD

**Issue by CaseyLeask** [addyosmani/grunt-uncss#16]
I'm having issues with the basic markup provided as part of `yo webapp`:

``` html
        <!-- build:css(.tmp) styles/main.css -->
        <link rel="stylesheet" href="styles/main.css">
        <!-- endbuild -->
```

I'm not familiar enough with Grunt plugins to fix this one just yet. `grunt-contrib-cssmin` seems to respect the [alternate search path](https://github.com/yeoman/grunt-usemin#blocks).

**Comment by trask** [comment]
@kuus +1 thanks!
