### ISSUE TITLE
arbitrary classes stripped out

### ISSUE THREAD

**Issue by JoernT** [addyosmani/grunt-uncss#160]
I have a fairly complex but static HTML page and applying uncss leads to a resulting CSS file that misses some of the CSS classes present in the HTML page. The matchers are not really complex - something like '.band-features .expandable'.

I've looked for problems in the CSS but couldn't find anything obvious. Interestingly enough it's not breaking at a certain point and stop processing but leaves out classes somewhere in the middle of the page and then continues to process correctly. 

I've put the relevant files into a gist here: https://gist.github.com/JoernT/b1c23bea5b02b363ecd2

As an example the matchers starting with '.band-features' are completely missing in the resulting index.min.css. 

Any idea what could have gone wrong? Thanks for looking into it.

**Comment by XhmikosR** [comment]
The ignore accepts regexes so make sure they are valid. Either way, this is an upstream issue.
