### ISSUE TITLE
How it works, and process to identify and troubleshoot

### ISSUE THREAD

**Issue by cybercussion** [addyosmani/grunt-uncss#163]
Hi,
Put a larger project against grunt-uncss and I'm finding it leans it out too much.  All the injected animation CSS classes are toast, and much of the stuff I thought PhantomJS was supposed to pluck out.

Is there a flow of how this project processes HTML, JS and CSS or any more rich logging options so its more apparent what its doing after you type 'grunt' in the CLI?  Its hard to identify if a CDN link to a javascript file just ends its JS search or if its even looking at all the JS present in the project.

Example: it seems like the project needs absolute paths to the files <script src="/...
That clears some reference errors, but I might not want relative paths on my project.
I think adding options, htmlroot "/" might solve this?

Bulk of my issue however seems to be PhantomJS not catching styles that are being used and I'm not certain of there is something to enable/troubleshoot that.

So .collapse.in {...} for example with bootstrap is getting wiped out as well as .collapsing {...}

**Comment by XhmikosR** [comment]
This is an upstream issue; you should ask in the uncss repository.
