### ISSUE TITLE
Handling of `//` protocol resolving

### ISSUE THREAD

**Issue by ArmorDarks** [addyosmani/grunt-uncss#164]
Hi

Seems that similar to #13 error appeared again in 0.4.0 and higher versions:

``` coffee
###
Uncss
https://github.com/addyosmani/grunt-uncss
Remove unused CSS
###
module.exports = ->
  @config 'uncss',
    build:
      options:
        htmlroot: 'build'
      files: [
        src: 'build/{,**/}*.html'
        dest: build/assets/styles/style.tidy.css'
      ]
```

```html
	<!-- Fonts -->
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700&amp;subset=latin,cyrillic">
```

results in:
![39d5n5](https://cloud.githubusercontent.com/assets/4460311/6970136/3160d156-d97c-11e4-9fab-c86080431367.png)

Please note that there is nowhere can be found path `build\css` in project or microtemplate's variables, while actuals project's css stored in `build\assets\styles`

Using of full protocol name `http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700&amp;subset=latin,cyrillic` fixes that issue, but it should work with `//` too I guess

In 0.3.8 all works fine

**Comment by XhmikosR** [comment]
Upstream issue; report it there.

**Comment by ArmorDarks** [comment]
Sure.

Ref: https://github.com/giakki/uncss/issues/164
