### ISSUE TITLE
Cyrillic paths regression

### ISSUE THREAD

**Issue by ArmorDarks** [addyosmani/grunt-uncss#165]
Hi

It seems that some of newer versions introduced regression in handling of cyrillic paths.

If any path to htmls will contain cyrillic characters, task will simply stuck forever on that stage:

```
Running "uncss:build" (uncss) task
```

I'm not sure which version exactly introduced that issue, but last time I've used grunt-uncss `0.3.8` with version of uncss `0.8.1` — everything worked fine. Seems that regression was introduced somewhere after `0.10.0`.

Reverting to `0.3.8` fixes issue.

**Comment by XhmikosR** [comment]
Seems like an upstream issue then; report it there.

**Comment by ArmorDarks** [comment]
Hi

Sure, thanks.

Just wanted to ensure that it isn't task error before reporting it there.

Just in case, relevant issue in `uncss` repository: https://github.com/giakki/uncss/issues/163
