### ISSUE TITLE
Fatal error: UnCSS & Typekit

### ISSUE THREAD

**Issue by foobartel** [addyosmani/grunt-uncss#169]
After updating to the latest version 0.4.2 it seems there is a new behaviour which results in a fatal error, with UnCSS somehow trying to parse a Typekit URL. I haven't seen this issue with the previous version. 

```bash
~/Sites/repos/missed-in-hkg (master) grunt uncss
Running “uncss:dist” (uncss) task
Fatal error: uncss/node_modules/css: unable to parse http://use.typekit.net/c/1a04cf/1w;proxima-nova,2,b5t:P:n3,b5w:P:n4/k?3bb2a6e53c9684ffdc9a9bf41d5b2a62183a574751fd848f787439ef36ae423e0294bf618b0faa6759749a087087087 :
missing ‘{‘ near line 13:1
	8:        	</head>
	9:        	<body>
	10:        		<h1>403 - Forbidden</h1>
	11:        	</body>
	12:        </html>
	13:     -> 
```
Should this be an expected behaviour?

A current workaround to fix this for now is to include Typekit in the `ignoreSheets` option: 

```js
options: {
  ignoreSheets : [/use.typekit/]
}
```

**Comment by XhmikosR** [comment]
This seems like an upstream issue. Please ask there.
