### ISSUE TITLE
Fatal error: Cannot read property 'stdin' of null

### ISSUE THREAD

**Issue by alephyud** [addyosmani/grunt-uncss#171]
Can't get `grunt uncss` working with multiple resulting files. When using the following run configuration

``` js
uncss: {
    dist: {
        options: {
            htmlroot: "./uncss"
        },
        files: {
            './static/css/cover.css': ['./uncss/index.html'],
            './static/css/styles.css': ['./uncss/page1.html', './uncss/page2.html']
        }
    }
},
```

I'm getting `Fatal error: Cannot read property 'stdin' of null`. When I leave only one record in `files`, everything works fine.

Seems like this is related to https://github.com/giakki/uncss/issues/136. Does anyone else have the same problem?

**Comment by thomaswmanion** [comment]
Having this too.

**Comment by jbhaywood00** [comment]
I'm getting this when running multiple tasks at once from the default task.  Actually, sometimes it works and sometimes it throws the error.  However, if I run the particular task that contains uncss with multiple files all by itself it works fine every time.  I'm assuming it's some kind of race condition.

**Comment by nuragic** [comment]
Hi! Same issue here...

**Comment by addyosmani** [comment]
This hasn't yet been solved over on https://github.com/giakki/uncss/issues/136. I'm quite sure we're waiting on it to be resolved.

**Comment by alephyud** [comment]
For the time being, I'm using a workaround for this: if there are several files, they are processed in order with `async`. Submitted it as a pull request https://github.com/addyosmani/grunt-uncss/pull/178 - up to you whether it is needed in the master branch as giakki/uncss#136 is hopefully going to be resolved sooner or later.

**Comment by addyosmani** [comment]
Just confirming that this isn't yet addressed upstream unfortunately. Will take a look at #178. Thank you for working on a workaround.

**Comment by XhmikosR** [comment]
Is this still an issue with the latest version?
