### ISSUE TITLE
How do I set up PhantomJS to work with uncss?

### ISSUE THREAD

**Issue by shanecarmody** [addyosmani/grunt-uncss#173]
Hey,

I just started checking out uncss today and I was wondering how I can set up PhantomJS on my machine to work with it? I have installed uncss correctly and it runs but I get this error:

`Fatal error: PhantomJS: Cannot open about:blank`

I don’t think I ever had PhantomJS installed on my machine so I installed it with npm:

`npm install -g phantomjs`

All good up to that point but then I try running `grunt uncss` again and I get the same error… so I’m not really sure what I’m supposed to do or how these two tools are supposed to interact with each other. Here is my Gruntfile.js:

``` js
module.exports = function(grunt) {

    // Project configuration.
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        uncss: {
            dist: {
                files: {
                    'style.css': ['*.php']
                }
            }
        },

        sass: {
            dist: {
                options: {
                    style: 'compressed'
                },
                files: {
                    'style.css': 'scss/style.scss'
                }
            }
        },

        watch: {
            sass: {
                files: ['scss/**/*.scss'],
                tasks: ['sass'],
            },
            livereload: {
              options: { livereload: true },
              files: ['scss/**/*.scss'],
            },
        },

    });

    grunt.loadNpmTasks('grunt-uncss');
    grunt.loadNpmTasks('grunt-contrib-sass');
    grunt.loadNpmTasks('grunt-contrib-watch');

    // Default task(s).
    grunt.registerTask('default', ['watch']);

};
```

I’m not that experienced with PhantomJS obviously but I’m thinking this is either to do with PhantomJS or maybe because uncss doesn’t take .php files as input?

Thanks for the task!

**Comment by thedigitalman** [comment]
I have the same issue

**Comment by Bobu77** [comment]
Same issue here for me. Even with html files.

**Comment by timbomckay** [comment]
Same

**Comment by knight00931** [comment]
I got the same problem, I am using Node.js 4.2.1, npm 2.14.7, grunt 0.4.5.

**Comment by gregbriandavis** [comment]
+1 for me.
No one has solved this yet? I am also on El Capitan.

**Comment by morteza-gho** [comment]
Hi.
I solved the problem by change the file type. convert (.php) file to (.html) file.
after uncss, delete (.html) file.

**Comment by kchez** [comment]
Really looking forward to seeing this in action after reading some blogs about it.
I'm getting the same error but on different file type, `cshtml`.  I haven't installed PhantomJS as it wasn't included in the README.md as being a required resource.
Any help would be appreciated.

Code:
```
uncss: {
  dist: {
    files: [
      {
        src: './Views/**/*.cshtml',
        dest: './Themes/Styles/css/tidy.css'
      }
    ]
  }
},
```

**Comment by stavarengo** [comment]
+1
