### ISSUE TITLE
Fatal error: Cannot read property 'stdin' of null

### ISSUE THREAD

**Issue by ereddate** [addyosmani/grunt-uncss#179]
Fatal error: Cannot read property 'stdin' of null

uncss:{
  a:{
     files:{
         "aaa/bbb.css":["aaa/bbb.html"]
      }
  }
}

**Comment by ereddate** [comment]
找到原因了，是因为你的代码里好多process.stdin没有做是否存在的判断。因为process=null或process.stdin == null所以报错。

**Comment by XhmikosR** [comment]
https://github.com/addyosmani/grunt-uncss/issues/179
