### ISSUE TITLE
WP 4.4.1 Emoji

### ISSUE THREAD

**Issue by RJRandell79** [addyosmani/grunt-uncss#181]
Seem the latest Wordpress 4.4.1 version throws an TypeError when evaluating 'e.getImageData(16,16,1,1).data.toString()' within a local development environment although the task successfully completes. This appears to be due to the WP's Emoji character set. The call to the function is within wp-includes/formatting.php (line 4584)  and does not seem to be present in WP versions prior to 4.4.1.

Full snippet below:
http://xxxxxxx/contact-us/:18 in d
http://xxxxxxx/contact-us/:18
http://xxxxxxx/contact-us/:18
TypeError: 'undefined' is not a function (evaluating 'e.getImageData(16,16,1,1).data.toString()')

Easiest workaround seems to be is to disable the emojis via the theme's functions.php by adding the following lines to the file. This seems to stop the errors being generated:
remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
remove_action( 'wp_print_styles', 'print_emoji_styles' );
remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
remove_action( 'admin_print_styles', 'print_emoji_styles' );

Thought I would post it here if anyone is having a similar issue. Thanks.

**Comment by XhmikosR** [comment]
I don't see how this can be related to grunt-uncss. It's an upstream issue so try reporting it there.
