### ISSUE TITLE
Nested class with sass

### ISSUE THREAD

**Issue by celsomtrindade** [addyosmani/grunt-uncss#185]
Is there a way to deal with nested classes on a better way when using it from sass? For example, I have this code:

```sass
.button {
    background: #cde;
    color: white;
    height: 48px;
    &.active {
      background: blue;
   }
}
```

And its going to generate this class:

```css
.button.active {}
```

Is there a way to add `.active` to ignore options and make it recognize even this `.button.active` ? Because right now I have to add it all to the ignore option.

Since I'm dealing with an AngularJs app, this is going to be a lot of manually job.

**Comment by XhmikosR** [comment]
Just use the ignore option properly; it accepts regex.

So this should work

```js
ignore: [
  /\.active/
]
```
