### ISSUE TITLE
urls options not working

### ISSUE THREAD

**Issue by redayoub** [addyosmani/grunt-uncss#187]
I'm trying to passe urls instead of html files, but I always get the error : Warning: Destination (web/css/dist/frontend.css) not written because src files were empty. Use --force to continue.

```javascript
uncss: {
    dist: {
        options: {
            stylesheets  : ['web/css/frontend.css'],
            urls: ['http://localhost:8000/']
        },
        files: {
            'web/css/dist/frontend.css': [
                'http://localhost:8000/'
            ]
        }
    }
}
```

**Comment by XhmikosR** [comment]
https://github.com/addyosmani/grunt-uncss/issues/142
