### ISSUE TITLE
uncss fails due to CDN paths

### ISSUE THREAD

**Issue by lt7** [addyosmani/grunt-uncss#189]
https://github.com/addyosmani/grunt-uncss/issues/51 <- this should be reopened, issue is still occuring on 0.5.2

**Comment by XhmikosR** [comment]
If this is an issue, it's an an upstream issue.

**Comment by lt7** [comment]
Any chance of identifying where upstream so it can be addressed ?

**Comment by XhmikosR** [comment]
Upstream means uncss itself.
