### ISSUE TITLE
Uncss fails after updating graphics card

### ISSUE THREAD

**Issue by VeliV** [addyosmani/grunt-uncss#191]
I updated my graphics card and now the same version of uncss that I was using does not work anymore. Here is the output.

Running "uncss:target" (uncss) task
Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Fatal error: Cannot assign to read only property 'message' of 3221225477

**Comment by XhmikosR** [comment]
This isn't an issue with grunt-uncss. Try uncss but judging from the crash it's phantomJS that's crashing so you should report the issue there.
