### ISSUE TITLE
What about dynamically added classes?

### ISSUE THREAD

**Issue by valnub** [addyosmani/grunt-uncss#193]
From what I understand, uncss parses html, scans for classes and uses this information to remove unnecessary css code from stylesheets.

But what about classes which are dynamically added via JavaScript during runtime? From what I understand, the styles for these classes would be missing since uncss removed them.

Also, what about frameworks like e.g. Foundation5? There also might be a chance that these UI frameworks add classes dynamically during runtime as well.

**Comment by RyanZim** [comment]
@valnub Uncss runs the html through PhantomJS, a headless web browser. Any classes added by the JS during the page load will be found by uncss; classes added by user interaction have to be manually ignored using the `ignore` option.

**Comment by valnub** [comment]
@RyanZim Hi, thanks for your reply. Why should classes added by user interaction be manually ignored? If they're ignored, the styles for those classes would be missing in the stylesheet that cssmin generates, or not?

**Comment by RyanZim** [comment]
Sorry for the misunderstanding; when you `ignore` a class, uncss will not remove it, even if it does not find it in the html.

**Comment by valnub** [comment]
@RyanZim Ah, thanks for clarify this. But this means, that I have to know all classes which could be potentially triggered by uncss and then manually set them to ignore, right?

I think this is difficult enough for own code, especially when there is a lot of it, but what about code from 3rd party libs like e.g. Foundation5 or SwiperJS? I don't know which classes could be added via user interaction since I didn't write those libs/frameworks.

**Comment by RyanZim** [comment]
@valnub I know; you have to do some work in the developer console to figure it out. If you make an ignore list for a popular framework, please submit it to the uncss wiki so others can use it.

**Comment by valnub** [comment]
Alright, thanks for your help, Ryan
