### ISSUE TITLE
uncss use first file for all other

### ISSUE THREAD

**Issue by thomas2411** [addyosmani/grunt-uncss#195]
I use grunt-uncss which is configured like this:

```
    uncss: {
        options: {
            ignoreSheets: [/fonts.googleapis/]
        },
        dist: {
            files: [
                {
                    dest: 'dist/css/site1.css', src: ['src/site1.html']
                },
                {
                    dest: 'dist/css/site2.css', src: ['site2.html']
                },
                {
                    dest: 'dist/css/site3.css', src: ['site3.html']
                }
            ]
        }
    },
```

In site1.html, site2.hml, site3.html I have linked the same CSS files from assets dir and one files which is distinct for each of these pages, like this:

```
<!-- build:css css/site1.min.css -->
<link rel="stylesheet" href="assets/plugins/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="assets/css/app.css">
<link rel="stylesheet" href="assets/css/blocks.css">
<link rel="stylesheet" href="assets/css/one.style.css">
<link rel="stylesheet" href="assets/css/footers/footer-v7.css">
<link rel="stylesheet" href="assets/plugins/font-awesome/css/font-awesome.css">
<link rel="stylesheet" href="assets/css/app.style.css">
<link rel="stylesheet" href="assets/css/custom.css">
<link rel="stylesheet" href="site1/styl.css">
<!-- /build -->
```

It worked OK but I don't know why it stopped. Now for each sites it takes styl.css file from the first in the configuration, which is site1. 
So in the end each site has style.css from site1
I use MAC OS X Sierra (recently updated). My package.json looks like this:

```
{
  "name": "myname",
  "version": "1.0.0",
  "description": "BlaBla",
  "license": "private",
  "devDependencies": {
    "grunt": "v1.0.0",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-cssmin": "^1.0.1",
    "grunt-contrib-htmlmin": "^2.0.0",
    "grunt-processhtml": "^0.4.0",
    "grunt-uncss": "^0.6.1"
  }
}
```

**Comment by romanlelek** [comment]
Hello, is there any update on this issue? I am having the same problem.

Thank you.

Best regards,
Roman

**Comment by XhmikosR** [comment]
Does this happen  with uncss itself? If not it would help if you could
provide a small test repository and even see when this started to break.

**Comment by romanlelek** [comment]
Well, I use only grunt-uncss, but I assume that the same problem will be wit uncss itself. 

As far as I remember, it started to break after updating from  El Capitan to Sierra.

**Comment by XhmikosR** [comment]
Well if it happens with uncss itself you will need to report it there. If
not I can try looking into it bit 1 I don't have Mac and 2 I need a test
repo.
