### ISSUE TITLE
Regex in src urls

### ISSUE THREAD

**Issue by therayess** [addyosmani/grunt-uncss#199]
Trying to use url src as a file input, my url is a details page with parameters (id for example), my code is like this:

```js
files: [{
	    nonull: true,
	    src: ['http://sdfrontend.com/course/single'],
	    dest: 'frontend/web/css/single.css'
	}]
```

the actual page url is like this:
http://sdfrontend.com/course/single?id=61

Running uncss on that url won't match and won't work, i tried using regex in the src like so:

```js
src:['http:\/\/sdfrontend.com\/course\/single(\?|\&)([^=]+)\=([^&]+)']
```

didn't work, tried other regex's too but also didn't work.

How can i define the src to be a url with parameters ?

Thanks for your time

**Comment by therayess** [comment]
any help on this please? i'm sure it's been done before but i'm missing the how-to...any feedback is appreciated. thanks

**Comment by XhmikosR** [comment]
If this doesn't work with uncss itself, there are not a lot you can do apart from opening an issue there. So, try that first.

**Comment by therayess** [comment]
I will try there then, thanks
