### ISSUE TITLE
JS errors without inline scripts

### ISSUE THREAD

**Issue by Romkond** [addyosmani/grunt-uncss#200]
Hi,
nodejs 6.11.0. I commented all the inline js (actually there was just GA, Metrika and Disqus). Other js-code is hidden in files, but I see numerous errors after uncss starts. They begin like this:
`Running "uncss:dist" (uncss) task
SyntaxError: Unexpected token '{'
 
  local:239 in setContent
  :2
TypeError: undefined is not an object (evaluating 'jQuery.noConflict')
 
  local:80 in global code
  :0 in setContent
  :2
You have included the Google Maps API multiple times on this page. This may cause unexpected errors.
 
  http://maps.google.com/maps/api/js?sensor=false:96 in bh
You have included the Google Maps API multiple times on this page. This may cause unexpected errors
...
`

Why? What's wrong? There's no inline js...
My Gruntfile.js is:
`module.exports = function(grunt) {

  // Project configuration. SFocus
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
	
	concat: {
		  files: [{
			nonull: true,
            src: ['public_html/assets/templates/thesite/css/*.css'],
            dest: 'public_html/assets/templates/thesite/css/concat.css'
			}]
        },
    },
    
 uncss: {
      dist: {
		options: {
          ignore: [/manager/],
		  stylesheets : ['public_html/assets/templates/thesite/css/concat.css'],
		  //ignoreSheets: [/fonts.googleapis/]//ignoring Google font
		  urls: [], //Overwritten in load_sitemap_and_uncss task
        },
		files: {
          'public_html/assets/templates/thesite/css/uncss.css': ['**/*.php']
		}
      },
    },

  });

  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-uncss');  
  
  grunt.registerTask('load_sitemap_json', function() {
    var sitemap_urls = grunt.file.readJSON('./sitemap.json');
    grunt.config.set('uncss.dist.options.urls', sitemap_urls);
});

  grunt.registerTask('default', [
   
	'concat',
    'uncss'
  ]);
 
};`
Thanks.
P.S. There are 2 places where "jQuery.noConflict" can be found - in script.js (initiations) and smooth-scroll.js

**Comment by XhmikosR** [comment]
First of all wrap your code into code blocks so it's easier to read your post.

Secondly, this is an upstream issue and not a grunt-uncss specific one. So please ask there.
