### ISSUE TITLE
Fatal error: Cannot communicate with PhantomJS process: PhantomJS exited unexpectedly: read ECONNRESET

### ISSUE THREAD

**Issue by Romkond** [addyosmani/grunt-uncss#201]
Hi there,

```
module.exports = function(grunt) {

  // Project configuration. SFocus
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
	
	uncss: {
		dist: {
			files: [{
				nonull: true,
				src: ['http://example.com','http://example.com/es','...'],
				dest: 'public_html/assets/templates/thesite/css/uncss.css'
			}]
		}
	},
	

  });

  grunt.loadNpmTasks('grunt-uncss');


  grunt.registerTask('default', [
    'uncss'
  ]);

  
};
```
I see the errors:

> Fatal error: Cannot communicate with PhantomJS process: PhantomJS exited unexpectedly: read ECONNRESET

or

> Fatal error: Cannot communicate with PhantomJS process: PhantomJS exited unexpectedly: write EPIPE

**Comment by XhmikosR** [comment]
Like I said in #200, this is an upstream issue. In order to confirm though, just try using uncss directly.

On a side note, I'm not even sure multiple urls are supported as input.

**Comment by Romkond** [comment]
You know, I have no idea what "upstream issue" is))... I've tried to run just one file... it worked. Then two... it worked. Then all of them again... and it also worked. So, IDK what it was.
