### ISSUE TITLE
Not taking into account the classes that are added through angular

### ISSUE THREAD

**Issue by Hulk11** [addyosmani/grunt-uncss#202]
Some features on my website are being distorted, for eg modals are not opening. It occurs when I add a uncss-ed version of bootstrap. Is it a bug or is there any solution to it?

**Comment by XhmikosR** [comment]
Upstream issue; please report there.

**Comment by Hulk11** [comment]
modal already loaded in the footer, just adding show,hide to class elements through angular. Are you sure it  is an upstream issue?

**Comment by XhmikosR** [comment]
1000% sure.

**Comment by Hulk11** [comment]
any idea how can it be removed?
would be very helpful of yours

**Comment by XhmikosR** [comment]
Just exclude those selectors. Again, ask upstream for more help, or even better search the upstream issues.

**Comment by Hulk11** [comment]
I tried upstream it didnt work... I think there may be some issue in jquery also.
