### ISSUE TITLE
does it conflict with JQuery

### ISSUE THREAD

**Issue by itsmerahul** [addyosmani/grunt-uncss#203]
is it conflicting with JQuery. None of the button involving jquery is working when I added css after processing through uncss

**Comment by itsmerahul** [comment]
I have checked... uncss also removes some classes that are defined in jquery, I have to manually add some selectors in the gruntfile to ignore. Is this still an upstream problem? and also the link you gave to upstream is not working

**Comment by XhmikosR** [comment]
I gave no link... upstream means the UnCSS repo. It's an issue with uncss itself and has nothing to do with grunt-uncss.
