### ISSUE TITLE
Grunt uncss fails silently mac

### ISSUE THREAD

**Issue by HugoHeneault** [addyosmani/grunt-uncss#206]
Here's my uncss config: 

```js
uncss: {
dist: {
    options: {
        ignore: [
            /ow-/
        ],
        timeout: 400,
        ignoreSheets : [
            /stages/
        ]
    },
    files: {
        'css/app.css': [
            "http://127.0.0.1/site"
        ]
    }
}
},
```

When I run it (with uncss 0.4.3), it just fails silently: 

```
hugo@hugo: grunt uncss
Running "uncss:dist" (uncss) task
hugo@hugo: $
```

Does anyone has this on mac?

Thanks

**Comment by XhmikosR** [comment]
v0.43 is pretty old. Try using the latest stable node.js version of your choice and the latest grunt-uncss version.

**Comment by HugoHeneault** [comment]
As you said, updating to latest grunt-uncss fixed the silent fail. 🎉 
Thanks!
