### ISSUE TITLE
Can't get grunt-css to work

### ISSUE THREAD

**Issue by XhmikosR** [addyosmani/grunt-uncss#46]
Hi.

I'm trying grunt-uncss with no success so far.

```
Running "uncss:dist" (uncss) task

C:\Users\xmr\Desktop\mpc-hc.org\node_modules\grunt-jekyll\node_modules\tmp\lib\tmp.js:261
  throw err;
        ^
mapReadFiles Error: could not find: C:\Users\xmr\Desktop\mpc-hc.org\_site\2012\06\21\welcome-to-the-new-website\_site\assets\css\pack-9c1b221d52ef3036ff1e34bf7ed3dce459533bf5.css
```

If I remove grunt-uncss everything works fine. I tried with and without specifying the stylesheet. If I skip it I end up with a zero byte tidy.css file and no errors.

My source is here  https://github.com/mpc-hc/mpc-hc.org/tree/grunt-uncss

Any help is appreciated, thanks!

PS. The task order in Gruntfile is a little weird at the moment because I wanted to get this working first. I'll switch to concatenate, uncss, then cssmin later.

**Comment by latestsmartphone** [comment]
I am not able to fix my error of UnCSS no style sheet found 
uncss: {
  dist: {
    files: {
      'dist/css/tidy.css': ['index.html']
    }
  }
},

**Comment by shnigi** [comment]
Same error. UnCSS: no stylesheets found as for @pawansoobhri
