### ISSUE TITLE
uncss fails due to cdn path

### ISSUE THREAD

**Issue by kristoferjoseph** [addyosmani/grunt-uncss#51]
# uncss fails when hitting a cdn css path
## Steps to reproduce

Add a url to a cdn based css resource in your html page:
`//cdnjs.cloudflare.com/ajax/libs/topcoat-icons/0.2.0/font/icomatic.css`
notice  `//` to allow for http & https loading

Run uncss against this page
## Expected

Uncss will recognize external resources and either load and export processed css
OR
skip and move on without error
## Actual

uncss errors with message:
`Fatal error: mapReadFiles Error: could not find: /cdnjs.cloudflare.com/ajax/libs/topcoat-icons/0.2.0/font/icomatic.css'
It assumes a local file path instead of recognizing it as an external resource.

**Comment by bbyler** [comment]
Possible need to reopen: ```grunt uncss``` with CDN CSS: 

```Fatal error: getaddrinfo ENOTFOUND {{cdn_domain}}```

**Comment by lt7** [comment]
Agreed, this should be reopened see the issue on version 0.5.2
