### ISSUE TITLE
fatal error: node_modules/css: property missing value near line 1:28445

### ISSUE THREAD

**Issue by ukeboyska** [addyosmani/grunt-uncss#56]
so i tried applying uncss to a new project, and now get this unexplained error when i run the task:

![fatal-error](https://f.cloud.github.com/assets/305925/2014244/bdf24ce0-87a1-11e3-9472-0bc4eeeab572.jpg)

as far as i can tell, i applied the grunt task the same exact way i did in my other project, which works fine now. what would be causing this error?

**Comment by manjula91** [comment]
hey I am facing a problem in my css and i am using minifies once.It just takes too long
