### ISSUE TITLE
Running with local virtualhost (using Laravel)

### ISSUE THREAD

**Issue by guilambert** [addyosmani/grunt-uncss#66]
Runs fine when I use the source's command line tool (https://github.com/giakki/uncss) :

(`{project}` just for privacy)

``` bash
uncss http://{project}.dev > public/assets/css/style.uncss.css
```

When trying to run it through grunt-uncss I get a : 

```
Destination (public/assets/css/style.uncss.css) not written because src files were empty.
```

I'm using load-grunt-tasks and load-grunt-config, could that cause an issue?

Here's my `uncss.js` task file:

``` js
module.exports = {
  dist: {
    files: {
      'public/assets/css/style.uncss.css': ['http://{project}.dev/']
    }
  }
};
```

Thanks in advance, can't wait to use this in production :+1:

**Comment by XhmikosR** [comment]
Does this still happen with 0.5.2?
