### ISSUE TITLE
Can’t make the task work without defining report option

### ISSUE THREAD

**Issue by LeBenLeBen** [addyosmani/grunt-uncss#78]
If I don’t define the "report" option, the task fail. Am I doing something wrong? Using version 0.3.0

```
uncss: {
    dist: {
        files: {
            'stylesheets/tidy.css': ['index.html']
        }
    }
}
```

```
TypeError: Cannot read property 'original' of undefined
    at /node_modules/grunt-uncss/tasks/uncss.js:48:98
    at /node_modules/grunt-uncss/node_modules/uncss/lib/uncss.js:224:20
    at /node_modules/grunt-uncss/node_modules/uncss/lib/uncss.js:170:16
    at /node_modules/grunt-uncss/node_modules/uncss/lib/lib.js:272:20
    at /node_modules/grunt-uncss/node_modules/uncss/node_modules/async/lib/async.js:142:25
    at /node_modules/grunt-uncss/node_modules/uncss/lib/lib.js:253:32
    at filterUnusedSelectors (/node_modules/grunt-uncss/node_modules/uncss/lib/lib.js:151:12)
    at async.eachSeries.callback.stylesheet.rules (/node_modules/grunt-uncss/node_modules/uncss/lib/lib.js:246:24)
    at iterate (/node_modules/grunt-uncss/node_modules/uncss/node_modules/async/lib/async.js:134:13)
    at /node_modules/grunt-uncss/node_modules/uncss/node_modules/async/lib/async.js:145:25
```

```
uncss: {
    dist: {
        files: {
            'stylesheets/tidy.css': ['index.html']
        }
    },
    options: {
        report: 'min'
    }
}
```

```
File stylesheets/tidy.css created: 9.81 kB → 597 B

Done, without errors.
```

**Comment by karol-f** [comment]
@addyosmani Bug still exist if you use 'uncssrc' without 'report' flag. Regards.

**Comment by XhmikosR** [comment]
@karol-f: please provide a complete test case including the uncssrc file in order for us to test.

**Comment by karol-f** [comment]
@XhmikosR Sure, here you are:
UNCSS tasks definition
```
options: {
        uncssrc: '.uncssrc'
    },
    dist: {
        files: {
            'output/style.min.css': ['web/cont/**/*.html']
        }
    }
```

Not working with this .uncssrc
```
{
    "htmlroot": "web/cont",
    "ignore": [
        "/.somerule/",
    ]
}
```

Worjking with this .uncssrc (added  "report": "min")
```
{
    "htmlroot": "web/cont",
    "report": "min",
    "ignore": [
        "/.somerule/",
    ]
}
```

If you need something else please let me know. Regards.

**Comment by XhmikosR** [comment]
OK, confirmed.

**Comment by XhmikosR** [comment]
@addyosmani: we basically don't calculate right the src bytes. I'll try to solve this unless you beat me to it :)

https://github.com/addyosmani/grunt-uncss/blob/master/tasks/uncss.js#L48 `report` here is unused
https://github.com/addyosmani/grunt-uncss/blob/master/tasks/uncss.js#L55 `report.original` is `undefined`; this is what we need to fix so that we use the original CSS files.

**Comment by XhmikosR** [comment]
After, looking into this closely, it's not our fault. We use uncss' `report.original` to get the original CSS as a `string`, which we pass to `maxmin`.

Now, it seems there's a conflict with the report option grunt-uncss has.

/CC @giakki @addyosmani

**Comment by XhmikosR** [comment]
Fixed upstream in https://github.com/giakki/uncss/commit/f1946df931bd56af9bd1d8f6951d30dc7516a91e.

We'll make a new release after we have a new uncss release with the fix (although it's not really needed if it's a minor version bump).
