### ISSUE TITLE
keep getting 'Fatal error: spawn EACCES' while running grunt uncss

### ISSUE THREAD

**Issue by zafar-saleem** [addyosmani/grunt-uncss#82]
I am keep getting following error while executing 'grunt uncss' command
Fatal error: spawn EACCES

here is how I am loading uncss in Gruntfile.js

uncss: {
    dist: {
        files: [
                { src: 'app/index.html', dest: 'dist/css/tidy.css' }
            ]
        }
    },

Node version I am using is "v0.10.13"

**Comment by icyflame** [comment]
@addyosmani 

I have this same problem. Currently, I am simply using `uncss` to target `development/dist/*.html`, and get the compressed CSS file.

**Error:**
```shell
Running "uncss:dist" (uncss) task
execvp(): Permission denied
Fatal error: spawn EACCES
```

**Comment by icyflame** [comment]
ping @addyosmani 

The above error still persists. I have tried the `chmod` command you suggested above. `uncss` alone does work. But, it does not work inside grunt.

**Comment by heygema** [comment]
this is funny @JoernT I did the exact same thing you did, and It works !

**Comment by ashkarrrahman** [comment]
@addyosmani , you saved my time.
Thanks
